### ISSUE TITLE
外部起動時にmongooseのエラーが出る

### ISSUE THREAD

**Issue by pollseed** [springhackathon/spa-service#24]
`pm2 start bin/www`

```
less ~/.pm2/logs/www-error-1.log

Error: connect ECONNREFUSED ::1:27017
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

**Comment by pollseed** [comment]
## 関連

### util.js

https://github.com/nodejs/node/blob/master/lib/util.js

### net.js

https://github.com/nodejs/node/blob/master/lib/net.js

**Comment by pollseed** [comment]
ポートが抑えられていたせい。同ネットワーク上で
