### ISSUE TITLE
heroku logs app error

### ISSUE THREAD

**Issue by pollseed** [springhackathon/spa-service#46]
```
2015-11-23T09:17:31.864631+00:00 heroku[slug-compiler]: Slug compilation started
2015-11-23T09:17:31.864641+00:00 heroku[slug-compiler]: Slug compilation finished
2015-11-23T09:17:34.180781+00:00 heroku[web.1]: Starting process with command `npm start`
2015-11-23T09:17:36.533195+00:00 app[web.1]: > fx-future-forecast@0.0.0 start /app
2015-11-23T09:17:36.533196+00:00 app[web.1]: > node ./bin/www
2015-11-23T09:17:36.533185+00:00 app[web.1]:
2015-11-23T09:17:36.533197+00:00 app[web.1]:
2015-11-23T09:17:37.118733+00:00 app[web.1]:
2015-11-23T09:17:37.118737+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-11-23T09:17:37.118738+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-11-23T09:17:37.118739+00:00 app[web.1]:                                       ^
2015-11-23T09:17:37.118744+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-11-23T09:17:37.118744+00:00 app[web.1]:     at Object.exports._errnoException (util.js:860:11)
2015-11-23T09:17:37.118745+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:883:20)
2015-11-23T09:17:37.118747+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-11-23T09:17:37.130492+00:00 app[web.1]:
2015-11-23T09:17:37.137785+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-11-23T09:17:37.138029+00:00 app[web.1]: npm ERR! node v5.0.0
2015-11-23T09:17:37.138933+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-11-23T09:17:37.139159+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-11-23T09:17:37.139383+00:00 app[web.1]: npm ERR! fx-future-forecast@0.0.0 start: `node ./bin/www`
2015-11-23T09:17:37.139603+00:00 app[web.1]: npm ERR! Exit status 1
2015-11-23T09:17:37.139905+00:00 app[web.1]: npm ERR!
2015-11-23T09:17:37.140206+00:00 app[web.1]: npm ERR! Failed at the fx-future-forecast@0.0.0 start script 'node ./bin/www'.
2015-11-23T09:17:37.140386+00:00 app[web.1]: npm ERR! This is most likely a problem with the fx-future-forecast package,
2015-11-23T09:17:37.140576+00:00 app[web.1]: npm ERR! not with npm itself.
2015-11-23T09:17:37.140749+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-11-23T09:17:37.140915+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-11-23T09:17:37.141156+00:00 app[web.1]: npm ERR! You can get their info via:
2015-11-23T09:17:37.146018+00:00 app[web.1]:
2015-11-23T09:17:37.141442+00:00 app[web.1]: npm ERR!     npm owner ls fx-future-forecast
2015-11-23T09:17:37.146316+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-11-23T09:17:37.146566+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-11-23T09:17:37.141780+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-11-23T09:17:37.137253+00:00 app[web.1]: npm ERR! Linux 3.13.0-66-generic
2015-11-23T09:17:37.784262+00:00 heroku[web.1]: Process exited with status 1
2015-11-23T09:17:37.798278+00:00 heroku[web.1]: State changed from starting to crashed
2015-11-23T09:17:37.799573+00:00 heroku[web.1]: State changed from crashed to starting
2015-11-23T09:17:40.080057+00:00 heroku[web.1]: Starting process with command `npm start`
2015-11-23T09:17:42.552758+00:00 app[web.1]:
2015-11-23T09:17:42.552787+00:00 app[web.1]: > fx-future-forecast@0.0.0 start /app
2015-11-23T09:17:42.552791+00:00 app[web.1]:
2015-11-23T09:17:42.552790+00:00 app[web.1]: > node ./bin/www
2015-11-23T09:17:43.673001+00:00 heroku[web.1]: State changed from starting to up
2015-11-23T09:17:43.729682+00:00 app[web.1]: npm ERR! Linux 3.13.0-66-generic
2015-11-23T09:17:43.735978+00:00 app[web.1]: npm ERR!     npm owner ls fx-future-forecast
2015-11-23T09:17:43.741066+00:00 app[web.1]:
2015-11-23T09:17:43.671481+00:00 app[web.1]:
2015-11-23T09:17:43.671485+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-11-23T09:17:43.671487+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-11-23T09:17:43.671488+00:00 app[web.1]:                                       ^
2015-11-23T09:17:43.671537+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-11-23T09:17:43.671538+00:00 app[web.1]:     at Object.exports._errnoException (util.js:860:11)
2015-11-23T09:17:43.671539+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:883:20)
2015-11-23T09:17:43.671540+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-11-23T09:17:43.712793+00:00 app[web.1]:
2015-11-23T09:17:43.730379+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-11-23T09:17:43.730751+00:00 app[web.1]: npm ERR! node v5.0.0
2015-11-23T09:17:43.731985+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-11-23T09:17:43.732366+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-11-23T09:17:43.732709+00:00 app[web.1]: npm ERR! fx-future-forecast@0.0.0 start: `node ./bin/www`
2015-11-23T09:17:43.733011+00:00 app[web.1]: npm ERR! Exit status 1
2015-11-23T09:17:43.733337+00:00 app[web.1]: npm ERR!
2015-11-23T09:17:43.733645+00:00 app[web.1]: npm ERR! Failed at the fx-future-forecast@0.0.0 start script 'node ./bin/www'.
2015-11-23T09:17:43.733966+00:00 app[web.1]: npm ERR! This is most likely a problem with the fx-future-forecast package,
2015-11-23T09:17:43.734244+00:00 app[web.1]: npm ERR! not with npm itself.
2015-11-23T09:17:43.734530+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-11-23T09:17:43.734925+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-11-23T09:17:43.735423+00:00 app[web.1]: npm ERR! You can get their info via:
2015-11-23T09:17:43.736457+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-11-23T09:17:43.741539+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-11-23T09:17:43.741837+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-11-23T09:17:44.587349+00:00 heroku[web.1]: State changed from up to crashed
2015-11-23T09:17:44.577993+00:00 heroku[web.1]: Process exited with status 1
2015-11-23T09:18:19.492748+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=forex-future-forecast.herokuapp.com request_id=44b615cc-0146-458a-b8cc-a811a47123cc fwd="36.2.7.191" dyno= connect= service= status=503 bytes=
2015-11-23T09:18:20.550170+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=forex-future-forecast.herokuapp.com request_id=bb41fca6-7c10-491d-96e3-57478769196e fwd="36.2.7.191" dyno= connect= service= status=503 bytes=
2015-11-23T09:18:46.470137+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=forex-future-forecast.herokuapp.com request_id=f93a9246-d9cb-4eb0-bb88-a01910822233 fwd="36.2.7.191" dyno= connect= service= status=503 bytes=
2015-11-23T09:18:47.818617+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=forex-future-forecast.herokuapp.com request_id=72cbc4db-b9a5-4707-ae21-2c317d75a425 fwd="36.2.7.191" dyno= connect= service= status=503 bytes=
2015-11-23T09:19:12.804438+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=forex-future-forecast.herokuapp.com request_id=e3772d9d-bf2c-4af2-9727-69beb0c20e82 fwd="36.2.7.191" dyno= connect= service= status=503 bytes=
2015-11-23T09:19:13.716496+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=forex-future-forecast.herokuapp.com request_id=b9f0ed8a-333b-4695-9c0e-6c8ffadd26d7 fwd="36.2.7.191" dyno= connect= service= status=503 bytes=
```

**Comment by Gaddict** [comment]
heroku config:set NODE_MODULES_CACHE=false --app forex-future-forecast

キャッシュしないようにすることで、
新しい値で上書きされるっぽい
